### PR TITLE
New Formula: squashfuse

### PR DESCRIPTION
**Pull request by sworisbreathing**
Squashfuse is a FUSE (filesystem in userspace) module for SquashFS.

### Why not homebrew-fuse?
My understanding is that homebrew-fuse is for modules that have a proper release cycle. squashfuse had a 0.1 release back in 2012, but there have been a number of updates on the `master` branch since then which are probably worth having, if you want to mount squashfs filesystems through fuse.

### CODE REVIEW

**Comment by dunn** [comment]
Is the 0.1 release definitely not worth including, then?

**Comment by sworisbreathing** [comment]
honestly, I'm not sure. I haven't tried it.

**Comment by dunn** [comment]
If it's not completely busted then my inclination is to put this in homebrew-fuse, and maybe poke the developers to tag a new stable release.

**Comment by sworisbreathing** [comment]
Okie dokie. I'll give that a shot.

**Pull request closed without merging**
