### PR TITLE
Update formula: kerl

### PR DESCRIPTION
**Pull request by fenollp**
`kerl` moved from spawngrid's to yrashk's (which is probably the same person)

### CODE REVIEW

**Comment by fenollp** [comment]
No idea why the CI fails

**Comment by fenollp** [comment]
Still no clue

**Comment by dunn** [comment]
@BrewTestBot test this please

**Comment by bfontaine** [comment]
The CI failed because… it’s a head-only formula :smile: 

Thank you for your contribution to Homebrew, @fenollp; We appreciate it!

**Pull request closed without merging**
