### PR TITLE
New formula: uhubctl

### PR DESCRIPTION
**Pull request by dardo82**
control USB hubs powering per-port

### CODE REVIEW

**Comment by dardo82** [comment]
So all the problem is that a command to switch on and off individual ports of an usb hub is not useful enough? I doubt that... -_-

**Comment by bfontaine** [comment]
@dardo82 The problem is not if it’s useful or not but if it’s maintained and not too niche. `uhubctl` hasn’t been updated in 9 months; doesn’t have a stable release and doesn’t seem popular so we’ll pass on this. Sorry!

However you can maintain the formula in your own tap ([see the doc here](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md)) which allows anyone to install it like any Homebrew formula.

The reasonning behind this is that we have to maintain those formulae and people will complain to us if it’s broken so we have to draw the line somewhere. Taps are a great way to split the maintenance burden; which is why we have so many of them ([head-only](https://github.com/Homebrew/homebrew-head-only), [games](https://github.com/Homebrew/homebrew-games), [python](https://github.com/Homebrew/homebrew-python), [php](https://github.com/Homebrew/homebrew-php), [science](https://github.com/Homebrew/homebrew-science), etc). Facebook has [its own tap](https://github.com/facebook/homebrew-fb), like [Atlassian](https://github.com/atlassian/homebrew-tap), [Pivotal Labs](https://github.com/pivotal/homebrew-tap), [Dart](https://github.com/dart-lang/homebrew-dart), etc.

**Comment by dardo82** [comment]
Not maintained for sure, too niche i wouldn't say at all... What would be a solution? For me to maintain it? For example writing a man page? Anyway i don't buy the premise: if it has not been updated in 9 months why do you suppose it will change in the future? If it will not change it will not break, then nothing to worry about complaints and maintenance.

**Comment by bfontaine** [comment]
> If it will not change it will not break, then nothing to worry about complaints and maintenance.

Say something change in the next OS X release that makes this not compatible with it; will the maintainer be here to fix the software? (this is a general question; not specifically targeting `uhubctl`)

> What would be a solution?

You can create a tap for the formula.

I ping-ed other maintainers to see if someone disagrees with me here.

**Comment by dardo82** [comment]
Yes, it vaguely make sense from the OS updates point of view, but it's not really convincing; anyway you can do as you like as long as it's clear that to manage collaboration arbitrary decisions are often effective.
What else could explain such a behaviour? You are saying you will not accept something that IS useful and IS working NOW because MAYBE in the medium FUTURE it'll not work. Are you sure it's sensible?

**Comment by bfontaine** [comment]
The point is that every single formula adds to the maintenance burden; and we all are volunteers contributing on our own spare time. The solution is to filter them in the core repo/taps and let anyone maintain any formula in their own tap. This is how all major Linux distributions manage their packages.

That way, the core maintainers don’t get overwhelmed; and everybody can have their formulae/packages. Isn’t it a great solution? :smile:

**Comment by dardo82** [comment]
Yes, i suppose you can do it that way if you want... Or otherwise you could do it right! :-P

**Comment by bfontaine** [comment]
Do you have any suggestion?

**Comment by dardo82** [comment]
Find less arbitrary criteria, so potential contributors can know in advance if their formula will get accepted and so are more willing to spend their time on something that will get be seen by the whole community, not like some obscure tap by who-knows-who.

**Comment by bfontaine** [comment]
You can know in advance; the rules are highlighted in the documentation: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff

> The software in question must be
> 
> - maintained (e.g. upstream is still making new releases)
> - known
> - stable (e.g. not declared "unstable" or "beta" by upstream)
> - used
> - have a homepage

You can also `brew audit --strict --online <formula>` before submitting.

**Comment by dardo82** [comment]
Exceptions make it less sure... Also: how do you define known and used?

**Comment by dardo82** [comment]
@DomT4 why can't you contribute to the conversation instead of just enforcing the law?

**Comment by DomT4** [comment]
Quoting myself elsewhere:

> Find less arbitrary criteria, so potential contributors can know in advance if their formula will get accepted 

If you read the contributing documents, you'll find we advise auditing Homebrew formula *in advance* with `brew audit --strict --online` which *would* have flagged the failure early on. The [Acceptable Formula](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Acceptable-Formulae.md#niche-or-self-submitted-stuff) guide is documented at that link, and you can find the `audit` instruction in the [Cookbook](https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Formula-Cookbook.md#basic-instructions).

> BTW zzz and wol aren't in a better situation about maintenance and updates but they are in the tap

These kinds of situations are precisely why we now have rules in place. We hit problems with accepting basically unmaintained software and then when it goes wrong (and it often does) we're left either maintaining it ourselves or killing it, by which point people may be relying on it. The rules are designed to prevent that sort of situation from happening so frequently.

Baptiste has answered a ton of replies from you in this thread. I have added to the answers provided. We have both pointed at the documentation and explained the reasoning. Barracking us is not the way to change our minds.

**Pull request closed without merging**
