### PR TITLE
New formula: kati

### PR DESCRIPTION
**Pull request by dalinaum**
kati is an experimental GNU make clone.

### CODE REVIEW

**Comment by dunn** [comment]
It's failing to build on Mountain Lion: http://bot.brew.sh/job/Homebrew%20Head-Only%20Pull%20Requests/233/version=mountain_lion/testReport/junit/brew-test-bot/mountain_lion/install___HEAD_Homebrew_head_only_kati/

**Comment by mistydemeo** [comment]
Looking like a C++11 issue? Does it need a C++11 compiler?

**Comment by mistydemeo** [comment]
Try adding `needs :cxx11` below the deps and `ENV.cxx11` at the top of the install method.

**Comment by dalinaum** [comment]
Thanks @dunn and @mistydemeo. I just pushed another commit.

**Comment by mistydemeo** [comment]
Looks like it builds! Thanks!

The test fails because ninja is not installed:

```
ninja.sh and build.ninja were generated, please run ./ninja.sh
==> ./ninja.sh
./ninja.sh: line 5: exec: ninja: not found
```

**Comment by dalinaum** [comment]
Oh I see. Because I had built Chromium on my laptop, ninja had been installed. I just pushed another commit.

**Comment by dalinaum** [comment]
```
* GitHub repository too new (<30 days old)
```

What can I do to pass these tests?

**Comment by mistydemeo** [comment]
Don't worry about that one. Given this is a Google project, I will make an exception.

**Comment by dalinaum** [comment]
:+1: Thanks so much. :)

**Pull request closed without merging**
