### PR TITLE
Add Cumulus (new formula)

### PR DESCRIPTION
**Pull request by radeksimko**

### CODE REVIEW

**Comment by radeksimko** [comment]
The build failure is related to this:
https://github.com/Homebrew/homebrew/pull/36030

**Comment by DomT4** [comment]
@BrewTestBot test this please

**Comment by DomT4** [comment]
Looks like you'll need to vendor `setuptools` here:

```
==> python -c import setuptools... --no-user-cfg install --prefix=/usr/local/Cellar/cumulus/HEAD --single-version-externally-managed --record=installed.txt

The required version of setuptools (>=2.0.1) is not
available, and can't be installed while this script is
running. Please install a more recent version first, using
'easy_install -U setuptools'.

(Currently using setuptools 1.1.6 (/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python))
```

Some audit issues as well:

```
==> audit problems
homebrew/head-only/cumulus:
 * HEAD resource "pyyaml": SHA1 checksums are deprecated, please use SHA256
 * HEAD resource "argparse": SHA1 checksums are deprecated, please use SHA256
 * HEAD resource "boto": SHA1 checksums are deprecated, please use SHA256
 * HEAD resource "simplejson": SHA1 checksums are deprecated, please use SHA256
 * HEAD resource "pystache": SHA1 checksums are deprecated, please use SHA256
 * Formula should have a desc (Description).
```

**Comment by DomT4** [comment]
Closing as dead. Please open a new updated PR if you'd like to.

**Pull request closed without merging**
