### PR TITLE
new formula: fluent-bit

### PR DESCRIPTION
**Pull request by cosmo0920**
Fluent Bit is a Data Collector for IoT

Question: Should I add `test` block to confirm installation correctly?

### CODE REVIEW

**Comment by cosmo0920** [comment]
> Question: Should I add test block to confirm installation correctly?

Self resolved.

`Fluent-Bit` has `fluent-bit` command! :)

**Comment by cosmo0920** [comment]
Hmm.., Jenkins reports curious result.... :/

**Comment by DomT4** [comment]
```

==> audit problems
homebrew/head-only/fluent-bit:
 * The homepage is not reachable (curl exit code 18)
```

Website is down apparently. Can't access it from my browser either. Maybe just use the Github repo link if the homepage has uptime problems.

**Comment by cosmo0920** [comment]
> Website is down apparently. Can't access it from my browser either. Maybe just use the Github repo link if the homepage has uptime problems.

Thanks. I used Github repo link instead.

**Comment by cosmo0920** [comment]
@BrewTestBot Test this please.

**Comment by cosmo0920** [comment]
Hmm, it seems to be fluent-bit build process violate sandbox contract.... :cry:

**Comment by xu-cheng** [comment]
Install is failed (which is unrelated to sandbox):
```
/tmp/fluent-bit20150828-33007-d2vcw4/lib/monkey/mk_core/include/mk_thread.h:31:1: error: unknown type name 'pthread_key_t'; did you mean 'pthread_attr_t'?
pthread_key_t mk_thread_scheduler;
^~~~~~~~~~~~~
pthread_attr_t
/usr/include/sys/_pthread/_pthread_attr_t.h:30:33: note: 'pthread_attr_t' declared here
typedef __darwin_pthread_attr_t pthread_attr_t;
                                ^
1 error generated.
```

**Comment by cosmo0920** [comment]
OK, I'll report this issue to upstream.
Please wait to resolve build failure at upstream.

**Comment by cosmo0920** [comment]
This build failing issue is already reported at upstream...: https://github.com/fluent/fluent-bit/pull/28

**Comment by cosmo0920** [comment]
Build failing issue fixed at upstream.

**Comment by cosmo0920** [comment]
@BrewTestBot Test this please.

**Comment by cosmo0920** [comment]
Hmm..., in my environment, build succeeded:

```log
% brew install --HEAD fluent-bit.rb -v
==> Installing fluent-bit from homebrew/homebrew-head-only
Warning: Formula file is modified!
Building from source because Library/Taps/homebrew/homebrew-head-only/fluent-bit.rb has local changes
To install from a bottle instead, run with --force-bottle
==> Cloning https://github.com/fluent/fluent-bit.git
git --git-dir /Library/Caches/Homebrew/fluent-bit--git/.git status -s
Updating /Library/Caches/Homebrew/fluent-bit--git
git config remote.origin.url https://github.com/fluent/fluent-bit.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
git checkout -f master --
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at f16b017 Merge pull request #28 from pandax381/pr_fix_build_clang_osx
==> Checking out branch master
...
==> Cleaning
==> Finishing up
ln -s ../Cellar/fluent-bit/HEAD/bin/fluent-bit fluent-bit
ln -s ../Cellar/fluent-bit/HEAD/include/fluent-bit fluent-bit
ln -s ../Cellar/fluent-bit/HEAD/include/mbedtls mbedtls
ln -s ../Cellar/fluent-bit/HEAD/lib/libfluent-bit.dylib libfluent-bit.dylib
ln -s ../Cellar/fluent-bit/HEAD/lib/libmbedtls.a libmbedtls.a
ln -s ../Cellar/fluent-bit/HEAD/lib/libmbedx509.a libmbedx509.a
==> Summary
🍺  /usr/local/Cellar/fluent-bit/HEAD: 84 files, 1.4M, built in 24 seconds
``` 

But Brew Test Bot log says build failing:


```log
==> brew install --verbose --build-bottle --HEAD Homebrew/head-only/fluent-bit FAILED
==> Installing fluent-bit from homebrew/homebrew-head-only
Warning: Formula file is modified!
Building from source because Library/Taps/homebrew/homebrew-head-only/fluent-bit.rb has local changes
To install from a bottle instead, run with --force-bottle
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20150828-29721-bo2zqr.sb nice /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/build.rb /usr/local/Library/Taps/homebrew/homebrew-head-only/fluent-bit.rb --build-bottle --verbose --HEAD
==> Cloning https://github.com/fluent/fluent-bit.git
git --git-dir /Library/Caches/Homebrew/fluent-bit--git/.git status -s
Updating /Library/Caches/Homebrew/fluent-bit--git
git config remote.origin.url https://github.com/fluent/fluent-bit.git
git config remote.origin.fetch +refs/heads/master:refs/remotes/origin/master
git fetch origin
git checkout -f master --
Already on 'master'
Your branch is up-to-date with 'origin/master'.
git reset --hard origin/master
HEAD is now at 3169118 out_td: use new I/O interface to flush data to the TD server
==> Checking out branch master
...
In file included from /tmp/fluent-bit20150828-29722-8e45mm/lib/monkey/mk_core/mk_thread_channel.c:25:
/tmp/fluent-bit20150828-29722-8e45mm/lib/monkey/mk_core/include/mk_thread.h:31:1: error: unknown type name 'pthread_key_t'; did you mean 'pthread_attr_t'?
pthread_key_t mk_thread_scheduler;
^~~~~~~~~~~~~
pthread_attr_t
/usr/include/sys/_types/_pthread_attr_t.h:30:34: note: 'pthread_attr_t' declared here
typedef __darwin_pthread_attr_t         pthread_attr_t;
                                        ^
1 error generated.
...
[ 56%] Built target mbedcrypto
make: *** [all] Error 2
```

**Comment by cosmo0920** [comment]
Fluent Bit repo owner added release tag.
I've registered Formula based on this PR to Homebrew repository https://github.com/Homebrew/homebrew/pull/43470.

**Pull request closed without merging**
